// these constants define boundaries of text in the ADS. For example faculty scholarly activity is between the text listed in FAC_SA_START and FAC_SA_END
const FAC_SA_START = "Faculty Scholarly Activity";
const FAC_SA_END = "Resident Appointments";
const RES_SA_START = "Resident Scholarly Activity";
const RES_SA_END = "List Of Residents On Leave";
const BOARD_DATA_START = "Physician Faculty Roster";
const BOARD_DATA_END = "Non-Physician Faculty Roster";
const LIC_START = 'Current Licensure Data';
const LIC_END = 'Academic Appointments';

// each time an action completes, progressbar advances by... (6 events adding up to 100%)
const PROGRESSBAR_ADVANCE = 17;	

// url where demo video is located
const DEMO_VIDEO_URL = 'ausam2_instructions.pdf';
const NOT_FOUND_HTML = "<p><i><b>Could not find any info for this category. This may happen when you cut and paste from a PDF rather than the web page generated by ADS. Please try again using the ADS web page.</b></i></p><p>&nbsp;</p><p>You can view a <a href='"+DEMO_VIDEO_URL+"'>how-to</a> here.</p><p>&nbsp;</p><p>If you think this is an error, please contact <a href='mailto:ngoyal1@hfhs.org'>Nikhil Goyal</a> with the entire text that you pasted in the box.</p>"

$(document).ready(function() {
	"use strict";
	$("#tabs").tabs();

	var progressbar = $( "#progressbar" ), progressLabel = $( ".progress-label" );
	progressbar.hide();
    progressbar.progressbar({
		value: false,
		change: function() { progressLabel.text( progressbar.progressbar( "value" ) + "%" );},
		complete: function() { progressLabel.text( "Complete!" ); }
	});

	$('#doit').on('click', function(){upload();});
	$('#clear').on('click', function(){reset_form();});
});

function reset_form() {
	// reset form - call default html function plus re-init previous data table results
	"use strict";
	$('#progressbar').progressbar("value", false).hide();
	$('#pmid_table').hide().data("flag_row", 0).data("nomatch_row",0);
	$('#pmid_table').find("tr:gt(0)").remove();
	$('#license').html('');
	$('#license').removeClass();
	$('#board_table').hide();
	$('#board_table').find("tr:gt(0)").remove();
}

function modal_dialog(title, htmltext) {
	"use strict";
	$('#modaldialog').html(htmltext);
	$('#modaldialog').dialog({
		modal: true,
		title: title,
		buttons: {
			Close: function() {$(this).dialog("close");}
		}
	});
}

function upload() {
	$.ajax({
		url: 'php/pdfread.php',
		type: 'post',
		data: new FormData($('#adsform')[0]),
		contentType: false,
		cache: false,
		dataType: 'text',
		processData: false,
	}).error(function(xhr){
		console.log("error with AJAX PDF upload");
		console.dir(xhr);
	}).success(function(response) {
		console.log(response);
		$('#adstext').val(response);
		process();
	});
}

function process() {
	// form submitted
	"use strict";
	if ($('#adstext').val().length<10) {
		modal_dialog("Missing Data", "Please copy-paste entire text of ADS annual update. You can view <a href='"+DEMO_VIDEO_URL+"'>instructions</a> here.");
		return false;
	}
	
	reset_form();
	$('#progressbar').show();
	var text=$('#adstext').val();
	var pb_val;

	// process PMIDs
	var fac_start=text.indexOf(FAC_SA_START);
	var fac_end=text.indexOf(FAC_SA_END);
	var res_start=text.indexOf(RES_SA_START);
	var res_end=text.indexOf(RES_SA_END);
	var subtext=text.substring(fac_start, fac_end)+text.substring(res_start, res_end);
	if (subtext.length<10) {
		// no scholarly activity block present
		$('#pmid_table').append('<tr><td colspan="4">'+NOT_FOUND_HTML+'</td></tr>');
		$('#pmid_table').show();
		pb_val=$('#progressbar').progressbar("value");
		$('#progressbar').progressbar("value", pb_val+PROGRESSBAR_ADVANCE+PROGRESSBAR_ADVANCE);
	}
	else {
		$.ajax({
			url: "/api/pubmed.php",
			data: {
				ay: $('#acyr').val(),
				pmidblock: subtext
			},
			dataType: "json",
			method: "POST",
			success: function(rval){
				pb_val=$('#progressbar').progressbar("value");
				$('#progressbar').progressbar("value", pb_val+PROGRESSBAR_ADVANCE);
				console.log(JSON.stringify(rval, null, 4));
				pmid_processed(rval);
			},
			error: function( xhr, status, errorThrown ) {
				modal_dialog( "AJAX error", "Unexpected result. Please contact <a href='mailto:ngoyal1@hfhs.org'>Nikhil Goyal</a>" );
				console.log( "Error: " + errorThrown );
				console.log( "Status: " + status );
				console.dir( xhr );
			}
		});
	}
	
	// Licensure data
	var lic_start=text.indexOf(LIC_START);
	var lic_end=text.indexOf(LIC_END);
	subtext=text.substring(lic_start, lic_end);
	if (subtext.length<10) {
		// no license block present
		$('#license').append(NOT_FOUND_HTML);
		pb_val=$('#progressbar').progressbar("value");
		$('#progressbar').progressbar("value", pb_val+PROGRESSBAR_ADVANCE+PROGRESSBAR_ADVANCE);
	}
	else {
		$.ajax({
			url: "php/license_check.php",
			data: {licblock: subtext},
			dataType: "json",
			method: "POST",
			success: function(rval){
				pb_val=$('#progressbar').progressbar("value");
				$('#progressbar').progressbar("value", pb_val+PROGRESSBAR_ADVANCE);
				console.log(JSON.stringify(rval, null, 4));
				lic_processed(rval);
			},
			error: function( xhr, status, errorThrown ) {
				modal_dialog( "AJAX error", "Unexpected result. Please contact <a href='mailto:ngoyal1@hfhs.org'>Nikhil Goyal</a>" );
				console.log( "Error: " + errorThrown );
				console.log( "Status: " + status );
				console.dir( xhr );
			}
		});
	}
	
	// Board certification data
	var board_start=text.indexOf(BOARD_DATA_START);
	var board_end=text.indexOf(BOARD_DATA_END);
	subtext=text.substring(board_start, board_end);
	if (subtext.length<10) {
		// no board cert data present
		$('#board_table').append("<tr><td colspan='3'>"+NOT_FOUND_HTML+"</td></tr>");
		$('#board_table').show();
		pb_val=$('#progressbar').progressbar("value");
		$('#progressbar').progressbar("value", pb_val+PROGRESSBAR_ADVANCE+PROGRESSBAR_ADVANCE);
	}
	else {
		$.ajax({
			url: "php/boardcert_check.php",
			data: {boardblock: subtext},
			dataType: "json",
			method: "POST",
			success: function(rval){
				pb_val=$('#progressbar').progressbar("value");
				$('#progressbar').progressbar("value", pb_val+PROGRESSBAR_ADVANCE);
				console.log(JSON.stringify(rval, null, 4));
				board_processed(rval);
			},
			error: function( xhr, status, errorThrown ) {
				modal_dialog( "AJAX error", "Unexpected result. Please contact <a href='mailto:ngoyal1@hfhs.org'>Nikhil Goyal</a>" );
				console.log( "Error: " + errorThrown );
				console.log( "Status: " + status );
				console.dir( xhr );
			}
		});
	}
}

function pmid_processed(rval) {
	// PMID data returned from AJAX
	"use strict";
	if (rval.pmid_count===0) {
		modal_dialog("No PMIDs found!", "No scholarly activity PMIDs were read in either the resident or faculty tables. <p>If you feel this is an error, please contact <a href='mailto:ngoyal1@hfhs.org'>Nikhil Goyal</a> with the entire text that you pasted in the box");
		return false;
	}

	if (rval.error.code!==0) {
		modal_dialog("Error processing text", "Please contact <a href='mailto:ngoyal1@hfhs.org'>Nikhil Goyal</a> with the entire text that you pasted in the box.<p><i>Error text: "+rval.error.text+"</i>");
		return false;
	}

	var flags=0, nomatch=0;
	$.each(rval.pmids, function(key, val) {
		var rowid='pmid_'+key;
		if (val.date_type==='epubdate') {val.date+=" <span class='epub_indicator'>(ePub)</span>";}
		else if (val.date_type==='entrezdate') {val.date+=" <span class='epub_indicator'>(Entrez Date)</span>";}
		
		if (val.date_found===1) {
			$('#pmid_table').append('<tr id="'+rowid+'"><td>'+key+'</td> <td nowrap>'+val.date+'</td> <td>'+val.authorstr+'</td> <td>'+val.title+'</td> </tr>');
			if (val.date_valid===0) {
				// pubdate is outside AY rage
				$('#'+rowid).children('td').addClass('flag_row');
				$('#pmid_table').data("flag_row", ++flags);
			}
		}
		else {
			// no date read from PMID record
			$('#pmid_table').append('<tr id="'+rowid+'"><td>'+key+'</td> <td colspan="4">Date could not be read (Incorrect PMID?)</td> </tr>');
			$('#'+rowid).children('td').addClass('nomatch_row');
			$('#pmid_table').data("nomatch_row", ++nomatch);
		}
	});
	$('#pmid_table').show();
	var val=$('#progressbar').progressbar("value");
	$('#progressbar').progressbar("value", val+PROGRESSBAR_ADVANCE);
}

function lic_processed(rval) {
	// Medical license date check returned from AJAX
	"use strict";
	
	if (rval.error.code!==0) {
		modal_dialog("Error processing text", "Please contact <a href='mailto:ngoyal1@hfhs.org'>Nikhil Goyal</a> with the entire text that you pasted in the box.<p><i>Error text: "+rval.error.text+"</i>");
		return false;
	}

	$('#license').append('<p>PD\'s License Expiration: '+rval.month+' '+rval.year+'. <i>'+rval.months_to_exp+' month(s) remain.</i></p>');
	if (rval.expired===1) {
		$('#license').addClass('flag_row');
	}
	else if (rval.months_to_exp<=6) {
		$('#license').addClass('nomatch_row');
	}
	var val=$('#progressbar').progressbar("value");
	$('#progressbar').progressbar("value", val+PROGRESSBAR_ADVANCE);
}

function board_processed(rval) {
	// Board check returned from AJAX
	"use strict";

	if (rval.error.code!==0) {
		if (rval.error.code===2) {
			$('#board_table').append("<tr><td colspan='3'>"+NOT_FOUND_HTML+"</td></tr>");
			$('#board_table').show();
			var val=$('#progressbar').progressbar("value");
			$('#progressbar').progressbar("value", val+PROGRESSBAR_ADVANCE);
		}
		else {
			modal_dialog("Error processing text", "Please contact <a href='mailto:ngoyal1@hfhs.org'>Nikhil Goyal</a> with the entire text that you pasted in the box.<p><i>Error text: "+rval.error.text+"</i>");
		}
		return false;
	}
	
	$.each(rval.results, function(key, val) {
		var rowid="staffid_"+key;
		var toappend='<tr id="'+rowid+'"><td>'+val.name+'</td><td>'+val.specialty+'</td><td>';
		if (val.issues!==0) {toappend+=val.descr;}
		else {toappend+="&nbsp;";}
		toappend+="</td></tr>";
		$('#board_table').append(toappend);
		if (val.issues===1) {$('#'+rowid).children('td').addClass('flag_row');}
		else if (val.issues===2) {$('#'+rowid).children('td').addClass('nomatch_row');}
	});

	$('#board_table').show();
	var pb_val=$('#progressbar').progressbar("value");
	$('#progressbar').progressbar("value", pb_val+PROGRESSBAR_ADVANCE);
}